version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ms_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: mysql
      POSTGRES_DB: ms_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  ms-usuarios:
    container_name: ms-usuarios
    image: jcedenon/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./ms-usuarios/Dockerfile
    ports:
      - "8001:8001"
#    env_file: ./ms-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: ms_usuarios
      DB_USERNAME: root
      DB_PASSWORD: mysql
      CURSOS_URL: ms-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  ms-cursos:
    container_name: ms-cursos
    image: jcedenon/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./ms-cursos/Dockerfile
    ports:
      - "8002:8002"
#    env_file: ./ms-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: ms_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: mysql
      USUARIOS_URL: ms-usuarios:8001
    networks:
      - spring
    depends_on:
      - postgres14
      - ms-usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring
